### ISSUE TITLE
CR-7iA(L) J3 joint limits incorrect

### ISSUE THREAD

**Issue by buhln** [ros-industrial/fanuc#334]
I had some trouble with the J3 axis of a CR-7iAL in real life. The robot stops the execution in the extreme positions. So I checked the limits in the [cr7ial_macro.xacro](https://github.com/ros-industrial/fanuc/blob/melodic-devel/fanuc_cr7ia_support/urdf/cr7ial_macro.xacro) file and compared it with the maximum value of the robot. I checked the maximum position three times each and get different max/min angles. I used the minimum plus and the maximum minus value in the xacro file and tested again. This time without problems. So I think the limits for J3 are still incorrect.
The same should be relevant for the CR-7iA model:  [cr7ia_macro.xacro](https://github.com/ros-industrial/fanuc/blob/melodic-devel/fanuc_cr7ia_support/urdf/cr7ia_macro.xacro)

Better values for J3 would be:
`<limit effort="0" lower="-0.7864" upper="3.0949" velocity="7.1558" />`

rqt shows also values in this span during error-free operation...
Furthermore, the actual limits are in sum 373 deg. This is much more than technical possible of the joint.

All other limits seems to be correct.

**Comment by gavanderhoorn** [comment]
I believe what you're describing are the usable limits. Those are not the same as the actual joint limits.

From the system variables of a CR-7iA/L:

```yaml
    lowerlims:
      - -2.967060e+00
      - -1.151917e+00
      - -2.439795e+00
      - -3.316125e+00
      - -2.094395e+00
      - -6.283185e+00
    upperlims:
      - 2.967060e+00
      - 1.745329e+00
      - 4.258603e+00
      - 3.316125e+00
      - 2.094395e+00
      - 6.283185e+00
```

note the values for J3: `(-2.439795e+00; 4.258603e+00)`.
